-- Mindful AI initial database schema

create extension if not exists pgcrypto;

-- Automatically maintain updated_at timestamps.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Student profile attached to a Supabase Auth account.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The eight curriculum weeks.
create table public.weeks (
  id bigint generated by default as identity primary key,
  week_number smallint not null unique
    check (week_number between 1 and 8),
  title text not null,
  theme text not null,
  description text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Activities belonging to each week.
create table public.activities (
  id uuid primary key default gen_random_uuid(),
  week_id bigint not null references public.weeks(id) on delete cascade,
  activity_type text not null
    check (
      activity_type in (
        'mindfulness',
        'ai_lab',
        'ethics',
        'reflection'
      )
    ),
  title text not null,
  content text,
  sequence_number smallint not null check (sequence_number > 0),
  duration_minutes integer
    check (duration_minutes is null or duration_minutes >= 0),
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_id, sequence_number)
);

-- A student's written response to an activity.
create table public.reflections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_id uuid not null
    references public.activities(id) on delete cascade,
  body text not null default '',
  status text not null default 'draft'
    check (status in ('draft', 'submitted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, activity_id)
);

-- Records activities completed by each student.
create table public.progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_id uuid not null
    references public.activities(id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, activity_id)
);

-- Minimal metadata only; no private prompt contents are stored here.
create table public.ai_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_id uuid references public.activities(id) on delete set null,
  message_count integer not null default 0 check (message_count >= 0),
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

-- Index foreign-key columns that will commonly be queried.
create index activities_week_id_idx
  on public.activities(week_id);

create index reflections_user_id_idx
  on public.reflections(user_id);

create index reflections_activity_id_idx
  on public.reflections(activity_id);

create index progress_activity_id_idx
  on public.progress(activity_id);

create index ai_sessions_user_id_idx
  on public.ai_sessions(user_id);

-- Keep updated_at fields current.
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger weeks_set_updated_at
before update on public.weeks
for each row execute function public.set_updated_at();

create trigger activities_set_updated_at
before update on public.activities
for each row execute function public.set_updated_at();

create trigger reflections_set_updated_at
before update on public.reflections
for each row execute function public.set_updated_at();

-- Enable Row Level Security on every application table.
alter table public.profiles enable row level security;
alter table public.weeks enable row level security;
alter table public.activities enable row level security;
alter table public.reflections enable row level security;
alter table public.progress enable row level security;
alter table public.ai_sessions enable row level security;

-- Published curriculum content can be read without an account.
create policy "Published weeks are readable"
on public.weeks
for select
to anon, authenticated
using (is_published = true);

create policy "Published activities are readable"
on public.activities
for select
to anon, authenticated
using (
  is_published = true
  and exists (
    select 1
    from public.weeks
    where weeks.id = activities.week_id
      and weeks.is_published = true
  )
);

-- Students can access only their own profiles.
create policy "Users can read their own profile"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

create policy "Users can create their own profile"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- Students can access only their own reflections.
create policy "Users can read their own reflections"
on public.reflections
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own reflections"
on public.reflections
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own reflections"
on public.reflections
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own reflections"
on public.reflections
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Students can access only their own progress.
create policy "Users can read their own progress"
on public.progress
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own progress"
on public.progress
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own progress"
on public.progress
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own progress"
on public.progress
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- Students can access only their own AI-session metadata.
create policy "Users can read their own AI sessions"
on public.ai_sessions
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own AI sessions"
on public.ai_sessions
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own AI sessions"
on public.ai_sessions
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Explicit client permissions.
grant select on public.weeks, public.activities
to anon, authenticated;

grant select, insert, update on public.profiles
to authenticated;

grant select, insert, update, delete on public.reflections, public.progress
to authenticated;

grant select, insert, update on public.ai_sessions
to authenticated;

-- One published record for testing the frontend connection.
insert into public.weeks (
  week_number,
  title,
  theme,
  description,
  is_published
)
values (
  1,
  'Presence and AI Awareness',
  'Knowing Yourself and the Machine',
  'A test curriculum record used to verify the mobile-to-database connection.',
  true
);